# Generated by Django 5.0 on 2024-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tax",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Tax percentage(%)"
            ),
        ),
    ]
